server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/listenmusic?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
