server:
  port: 8090

spring:
  devtools:
    restart:
      enabled: true
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/listenmusic?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
mybatis:
  configuration:
    map-underscore-to-camel-case: true



